### PR TITLE
Add support for PF LightBrick (LEDS)

### PR DESCRIPTION
**Pull request by rhempel**
All set to go! I may break this up into a separate wedo_lightbrick.c file eventually

### CODE REVIEW

**Comment by dlech** [comment]
Looks good to me.

**Comment by rhempel** [comment]
You want I should pull this one?

**Comment by dlech** [comment]
Go for it.

**Comment by rhempel** [comment]
I'm going to go ahead and delete the wedo-led and wedo-support branches while I'm in here

**Pull request merged**
