### PR TITLE
Wedo support

### PR DESCRIPTION
**Pull request by rhempel**
WeDo support is now working - please pull into the main tree.

### CODE REVIEW

**Comment by dlech** [comment]
I tested this using the dc-motor class with the rcx-motor driver to make sure you didn't break anything in the dc-motor class. It looks great. I had fun with a really long ramp time and throwing changes in `duty_cycle_sp` and `polarity` at it to see what it did - and it does what we want.

I still don't have access to a WeDo hub though, so I couldn't test anything else.

A few more things though:
1. You have some serious white space issues in the wedo files. Lots of spaces before tabs and some trailing whitespace.
2. You need to add the new module to the `ev3dev_defconfig` file using `./defconfig update`.
3. It might be nice to squash these commits, especially if you cleanup all the whitespace.

**Comment by rhempel** [comment]
I keep forgetting to check for whitespace - there's a kernel coding standard and a script that will check this - so I need to make a darned checklist so that it's second nature. I figured the commits get squashed when you merge the pull request into the jessie branch. The wed-support branch can then be deleted. Let me get the whitespace fixed up, and I'll issue a new pull request. Doc page is about 25% done now, it will go into its own section under `/docs/wedo/index.md` - unless it should be a tutorial...

**Comment by dlech** [comment]
> there's a kernel coding standard and a script that will check this - so I need to make a darned checklist so that it's second nature

I just use `git diff` with color=auto. It shows all "bad" whitespace in bright red.

> I figured the commits get squashed when you merge the pull request into the jessie branch.

Not unless I manually do it :wink:. It would be better if you do it because then you get to make the commit message.

> I'll issue a new pull request

No need for a new pull request. Just push to the wedo-support branch and this pull request will be automatically updated (even if you force push).

**Comment by dlech** [comment]
Oh, and if the docs are a "howto", then it would fit better as a tutorial. If it is a reference manual, then it would go elsewhere. However, the reference manual pages would be better if they were automatically generated from the kernel source code.

**Comment by dlech** [comment]
You missed all the spaces before tabs. Affected files are wedo_hub.c, wedo_motor.c, wedo_port.c, and wedo_sensor.c.

**Comment by dlech** [comment]
Squashing now...

**Pull request merged**
