### PR TITLE
Reduce LED power by using one LED in HALF brightness

### PR DESCRIPTION
**Pull request by prabindh**
In current board file, the EV3 LEDs are configured to LED_FULL brightness, and LEDs are triggered by same trigger.

This patch enables only one trigger, and enables only half power for the LEDs.

Alternatively, (1) an user-side script can be started at boot to switch off the LEDs totally on launch. (2) Further, switching off the LCD after boot can be considered to reduce power consumption, to get more battery life.

Please review.

### CODE REVIEW

**Comment by G33kDude** [comment]
I think that the half brightness during boot and off after boot is a good idea. By 

> LEDs are triggered by same trigger.

you mean both the red and green LED on their sides? The left and right sides are not on the same trigger

**Comment by dlech** [comment]
The `max_brightness` here is the maximum possible brightness of the LEDs. If we change these values, anyone depending on the `max_brightness` attribute will get an incorrect value. So, these changes don't make sense.

**Comment by prabindh** [comment]
@G33kDude - I meant, both left LEDs are triggered same, and both right LEDs are triggered same.

**Comment by prabindh** [comment]
@dlech - "anyone depending on the max_brightness attribute will get an incorrect value" - Well, max_brightness is itself relative.

**Comment by dlech** [comment]
We are using gpio-pwm to be able to control the brightness of the LEDs, so instead of having 255 steps of possible brightness values, with this patch, we would only have 127 or 0 possible steps. I really don't want' 0 possible steps. :wink:

**Comment by prabindh** [comment]
@dlech - I can make all to 127 instead of OFF then, atleast as starting point since it is only for the boot duration. Is that acceptable ?

**Comment by dlech** [comment]
These changes affect more than just the boot duration, so no, not acceptable.

**Comment by prabindh** [comment]
I think you meant - more than just "for" the boot duration. I still do not see why anyone will want to see a fully bright LED.
I will also look at the usermode scripts to turn these off post-boot.

**Comment by dlech** [comment]
Another thing to consider is that dimming the LEDs requires more CPU because we are just bit-banging GPIOs 100x per second to dim the LED. And the last thing we need at boot is more CPU usage.

**Comment by rhempel** [comment]
I'm with @dlech here - the LED on during the boot time is not a significant power draw - whenever I see "Let's optimize X by doing Y" my first reaction is "Show me that doing Y optimizes X and by how much"
In engineering, everything is a tradeoff - and sometimes it's just not worth it.
@prabindh - do not take this as meaning we don't like suggestions - we do appreciate all suggestionsk, especially if they come with patches. But that does not mean we need to accept them :-) You are, of course, free to modify your own copy of the source and use it as you see fit.

**Comment by prabindh** [comment]
@rhempel -  the LED is on throughout, not just during the boot time....The point @dlech raised and I need to confirm is the CPU usage.

**Comment by G33kDude** [comment]
I personally don't care how much power the LEDs draw, I just think that bright blinking lights can be distracting. The green LED is already significantly dimmer than the red one (though I can't say I have any idea how much the current draw from them differs), so I think that just blinking the green ones during boot would have a similar effect without the CPU overhead.

**Comment by prabindh** [comment]
I added a small patch for the startup scripts that reduce the LED brightness, please review, https://github.com/ev3dev/ev3dev-base/pull/1

**Comment by prabindh** [comment]
@rhempel @dlech  - Finally I found some time to rig up a measuring setup and added the information you requested in the below link.  Please check and comment if you feel there is an error in the measurement. I am getting a 24% reduction in current consumption with the patch.

http://robotpowered.org/ev3power.txt

> > the LED on during the boot time is not a significant power draw - whenever I see "Let's optimize X by doing Y" my first reaction is "Show me that doing Y optimizes X and by how much"
> > In engineering, everything is a tradeoff - and sometimes it's just not worth it.

**Comment by dlech** [comment]
I still can't accept this patch because it limits the usability of the LEDs and it cannot be changed without recompiling the kernel. I will accept a patch that makes this configurable though.

It would be super-awesome if you could set up the LEDs using device tree, but I will settle for making this configurable using a kernel command line option.

**Pull request closed without merging**
